name: ONNX CPU Selfcheck

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  selfcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Unit tests (CPU)
        env:
          EMBEDDINGS_MODE: none
        run: npm test --silent